apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-conf-dso
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "basic-auth.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob "conf/haproxy.cfg").AsConfig .) | indent 2 }}



