apiVersion: v2
name: demo-apim
description: A Helm chart for Kubernetes deploying Krakend, Keycloak & a CNPG cluster to provide API Gateway functionnality

type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: krakend
  version: "0.1.34"
  repository: "https://baboulinet-33.github.io/helm-charts"
  condition: krakend.enabled
- name: keycloak
  version: "24.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: keycloak.enabled
- name: cluster
  version: "0.0.11"
  repository: "https://cloudnative-pg.github.io/charts"
  condition: cluster.enabled
