apiVersion: v1
kind: Secret
metadata:
  name: db-app-user
type: kubernetes.io/basic-auth
data:
  username: YXBw # app
  password: cGFzc3dvcmQ= # password
---
apiVersion: v1
kind: Secret
metadata:
  name: db-super-user
type: kubernetes.io/basic-auth
stringData:
  username: cG9zdGdyZXM= # postgres
  password: cGFzc3dvcmQ= # password
