apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-nginx.fullname" . }}
  labels:
    {{- include "demo-nginx.labels" . | nindent 4 }}
    app: dso-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-nginx.selectorLabels" . | nindent 6 }}
      app: dso-nginx
  template:
    metadata:
      labels:
        {{- include "demo-nginx.selectorLabels" . | nindent 8 }}
        app: dso-nginx
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}