apiVersion: v1
kind: Service
metadata:
  name: demo-nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx
