{{- if .Values.vaultSecret.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "basic-auth.fullname" . }}
  labels:
    {{- include "basic-auth.labels" . | nindent 4 }}
spec:
  mount: {{ .Values.vaultSecret.mount }}
  path: {{ .Values.vaultSecret.vaultPath }}
  type: kv-v2
  vaultAuthRef: vault-auth
  destination:
    create: true
    name: {{ .Values.vaultSecret.destination.name }}
{{- end -}}