apiVersion: v2
name: basic-auth
description: A Helm chart for Kubernetes that provide a basicAuth to a web app
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: haproxy
  version: 2.2.0
  repository: "https://charts.bitnami.com/bitnami"
