
replicaCount: 1

image:
  repository: bitnami/nginx
  pullPolicy: IfNotPresent
  tag: "1.26.2"

imagePullSecrets:
- name: registry-pull-secret


service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1024Mi

vaultSecret:
  enabled: false


extraEnvVars: {}

basicAuth: {}

haproxy:
  global:
    compatibility:
      openshift:
        adaptSecurityContext: force
  
  existingConfigmap: "haproxy-conf-dso"

  service:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: http

  pdb:
    create: false

  networkPolicy:
    enabled: false

  serviceAccount:
    create: false

  ingress:
    enabled: true
    pathType: Prefix
    hostname: "monhostname.fr"
    path: /