apiVersion: v1
kind: Service
metadata:
  labels:
    component: prometheus-blackbox
  name: blackbox-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: "blackbox-http"
      protocol: TCP
      name: "blackbox-http"