apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-secrets
  annotations:
    myapp.config/postgres-host: postgres-postgresql.postgres.svc.cluster.local:5432
spec:
  vaultAuthRef: {{ .Values.vaultAuthRef }}
  mount: {{ .Values.vaultSecretMount }}
  path: dev/db
  type: {{ .Values.vaultSecretType }}
  refreshAfter: {{ .Values.vaultRefreshAfter }}
  destination:
    name: db-secrets
    create: true
    type: Opaque
    transformation:
      excludes:
      - .*
      templates:
        url:
          text: |
            {{`{{- $host := get .Annotations "myapp.config/postgres-host" -}}
            {{- printf "postgresql://%s:%s@%s/postgres?sslmode=disable" (get .Secrets "username") (get .Secrets "password") $host -}}`}}

