apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: docker-secret
spec:
  vaultAuthRef: vault-auth
  mount: {{ .Values.vaultSecretMount }}
  path: dev/dockerconfig
  type: {{ .Values.vaultSecretType }}
  refreshAfter: {{ .Values.vaultRefreshAfter }}
  destination:
    name: demo-pull-secret
    create: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates: 
        ".dockerconfigjson":
          text: |
            {{`
              {{- $registry := get .Secrets "registry" -}}
              {{- $username := get .Secrets "username" -}}
              {{- $password := get .Secrets "password" -}}
              {{- $config := (list $username ":" $password | join "" | b64enc)  -}}
              {{- dict "username" $username
                        "password" $password
                        "auths" (dict $registry $config) 
                        | mustToJson -}}
            `}}
