apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: foo-secrets
spec:
  vaultAuthRef: {{ .Values.vaultAuthRef }}
  mount: {{ .Values.vaultSecretMount }}
  path: foo
  type: {{ .Values.vaultSecretType }}
  refreshAfter: {{ .Values.vaultRefreshAfter }}
  destination:
    name: foo-secrets
    create: true
