apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-secrets
spec:
  vaultAuthRef: {{ .Values.vaultAuthRef }}
  mount: {{ .Values.vaultSecretMount }}
  path: {{ .Values.vaultSecretPath }}
  type: {{ .Values.vaultSecretType }}
  refreshAfter: {{ .Values.vaultRefreshAfter }}
  destination:
    name: db-secrets
    create: true
