apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: demo-keycloak-secrets-dev
spec:
    secretTemplates:
        - name: demo-keycloak-auth-secret
          stringData:
            KEYCLOAK_PASSWORD: ENC[AES256_GCM,data:bs/g5GHFkdXkNVaYsEeR+l2m,iv:orB60yv34h7RI7FAIoYzC7jcjzabQMR3wyZhYllRNa0=,tag:Erz3ONufUfDsOU27iu66JA==,type:str]
            KC_REALM_CLIENTSECRET: ENC[AES256_GCM,data:JGR/qdLvDU/Z4zC3u9cn2zGN/gzY,iv:3TKxISaDk2P5CSB0wPON8kbdGyub2gtmGNcsbclBwtE=,tag:8yJPadANpzVi1roIfUFb6Q==,type:str]
            KC_USER_ADMIN_PASS: ENC[AES256_GCM,data:8L35igg=,iv:RYmkddJfSgHHcpdqfI+B0x/Dbx3gFDr9M14TVrnc/3w=,tag:L3MRNylFhS7rxfiS8j2Tnw==,type:str]
            KC_USER_RW_PASS: ENC[AES256_GCM,data:H/rZFBXSZNMI,iv:uZJ3ArvNCg3jRpR1of8n2SKgYT86RIzvHf4xHJWpGMU=,tag:wonkpB4QVUMHgrEje1ygBg==,type:str]
            KC_USER_RO_PASS: ENC[AES256_GCM,data:x/3DPc3jWY0=,iv:0d/07p/pG+CKEl6U50coNWicHKLw7NQYOok0BC7XMhE=,tag:IVuLmFevNp1mC3Jk7E15cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMelRzMDBGSEdJMXdkaFgx
            TlJJTkRPYUdTMCtFUWIrQUNUOUZHOGNsQW1ZClNMNW1YcXZpcFN6MkgwekZtS3ds
            cG5kWnF4SGRqQi9aVitLTXVFRVBlWkkKLS0tIFhac2lYZVplVUd5aHRobkxvczIw
            S0NtdEYxQ3AwTXdmbjZpWTNTcVNReU0KXf0CON9bZb5TsgtMjcKzmVxBDalxX8Eq
            3xt8b63jYeRG5dcq/gvLoEHE4KAoNYyFVGWSGoBUTb8J1kZC5WOv/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T11:55:55Z"
    mac: ENC[AES256_GCM,data:PegcORSdCTR4+eCBo83ZkuomJuDDBvkPxAAIyT1AY4ZN3hS3vOP2mCIdagOjKJ+PzXQLSGYsCmbrLWXpoo7+7yM2lR/1wb9bj3nFJEZVAL3kxWTon0z39qfoYi0OZCW06I7es2ayOIu4Gttbl2ZhXFKnV7h10q64aC1Mm6n7+qg=,iv:Z38f7ViHJFWXoyzeLICFlwPzbO1rnx2qrvlLhaJ3VAg=,tag:+20ZJ2Mc2Vw/BJHXZJ/a8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
