apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: demo-keycloak-secrets-dev
spec:
    secretTemplates:
        - name: demo-keycloak-env-secret
          stringData:
            KC_REALM_CLIENTSECRET: ENC[AES256_GCM,data:rH+wZwzjsVuwMnVN,iv:hpiHV/W/lZ21M2jJOVfDHshRicF5caKAM+leo2ZWBCg=,tag:vnYnbNjtcjT5OXaCL+rQHg==,type:str]
            KC_USER_ADMIN_PASS: ENC[AES256_GCM,data:7SzM3Dw=,iv:faH1sH9jezV6sUzOL+X7LGpLL8ombEO3uiEnPh5ivc4=,tag:hUNx7xwIwEZuqDxTPw7w0Q==,type:str]
            KC_USER_RW_PASS: ENC[AES256_GCM,data:bEH8fxCpNhim,iv:W3zl/C+MRSte8WTMD/jgmcPgPP8Qq+Hh94qX2iG/HeA=,tag:ybvNVEk/nJ7FhJq+XxtiCw==,type:str]
            KC_USER_RO_PASS: ENC[AES256_GCM,data:+POLx3ubgqg=,iv:ZtZ6+S7G4nyRBXe6kLn8AI5YcQMe/+JfKWf/UIP7TQw=,tag:kFm8wkUwxVhJxElXpexTBQ==,type:str]
        - name: demo-keycloak-auth-secret
          stringData:
            KEYCLOAK_PASSWORD: ENC[AES256_GCM,data:LvGhiRM=,iv:XKgIGf00Rb8OwOzDUJKsAyyZAEORGdb7Yx3KH6YQsfI=,tag:PjIkorZFl+Zqfca7AFI4hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb09JblFzakN5TTJZYWZE
            WjZ0bTFKb2w3YzNSaUhGckZQUnc1U2hmcEdBCkkvNEtlODFDRis2anV4Q3RnZmFp
            VGFZSjZxQXVGZW5GTWl4RnVJeWNWSHcKLS0tIDAvZnpaOVZXV1p3MTIrUHpWRkVT
            OW9nNUh5R3ZCNU1kNzV6NmhIVVlsV28Kh/VOaA8a6cfyLd8zIKmtySWjFpS7X4+Z
            MXaQbqLfg9D/VPmdud1o3VbOXKo0Zx9uNGBK5b7R+VVtjykQCgkD+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T14:52:50Z"
    mac: ENC[AES256_GCM,data:pUOZVR0iWAsQbWK6ZepV2+sfQ/vfL5bHUAL8tqptNFqD8hqU2/ygxJpqNSynuuJxqEwTAqs/uRONF224LTln23YUM/4ptH0nq0LvoD9xCR2kptYOpZsWVe//gJwiYHWxCIl9rSukwuxP2U+ZWoxML+q8Fqzt01IImtN29aJtxvI=,iv:4OGoxvfLHJhyHW11sDDFYjxQLzkbb7vasGOk7qbzasc=,tag:5BAkFsFAcRcPsaHQXykP3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
