vaultAuthRef: vault-auth

vaultSecretMount: orgprch-projetdemo
vaultSecretPath: "db"

vaultRefreshAfter: 10m

vaultSecretType: kv-v1

rolloutRestartTargets:
- kind: Deployment
  name: busybox
- kind: Deployment
  name: busybox2